### ISSUE TITLE
New parameter in the database

### ISSUE THREAD

**Issue by DelloStritto** [ginnocen/MachineLearningHEP#536]
Dear all,
I added a new parameter in the LcpK0s database to select if the FONLL file is a root file or a csv file.
I did it because the fonll that was used before was for the 5TeV (and it was a csv file) while the fonll for 13TeV is a root file. 
You can still use the old file setting the new parameter to false  ----- isFONLLfromROOT: false
but you have to add it to your database.

**Comment by benedikt-voelkel** [comment]
Ciao @DelloStritto 
It's nice you added the description here! However, I am not sure whether people really read the issues regularly? I will add the field to all DBs including a brief comment on the field in each DB and then we can close this.
