### ISSUE TITLE
No need to reprocess the D0 to add the 1-2 GeV

### ISSUE THREAD

**Issue by ginnocen** [ginnocen/MachineLearningHEP#601]
@vkucera @benedikt-voelkel

**Comment by benedikt-voelkel** [comment]
@ginnocen @vkucera 
As we have discussed only the analysis has to be reprocessed and correct bin matching has to be set. After the skimming stage we already had the bin 1-2 GeV: https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/data/data_prod_20200304/database_ml_parameters_D0pp_zg_0304.yml#L35

I'll open a PR later today with updated V0M_perc analysis for D0 and the latest macro to produce teh final results

**Comment by ginnocen** [comment]
@benedikt-voelkel can we close this too?

**Comment by benedikt-voelkel** [comment]
@ginnocen yes, please. For some reason I lost all my rights here. Cannot merge PRs, cannot close issues and so on :D
