### ISSUE TITLE
Travis got coronavirus.

### ISSUE THREAD

**Issue by vkucera** [ginnocen/MachineLearningHEP#616]
The pylint checks performed by the Travis CI tool keep failing.
Travis always starts sneezing too much and the log gets too long.
Error message: 
> The job exceeded the maximum log length, and has been terminated.

**Comment by vkucera** [comment]
Workaround by @benedikt-voelkel #622

**Comment by benedikt-voelkel** [comment]
@vkucera it's cured :) I would say it's resolved
