### ISSUE TITLE
Add validation plotting function

### ISSUE THREAD

**Issue by ginnocen** [ginnocen/MachineLearningHEP#626]
Hello @njacazio. In the PR https://github.com/ginnocen/MachineLearningHEP/pull/625
I added a simple skeleton for producing plots of validation. The new function should read the file where you included all the validation histogram, build plots and save them to pdf.

**Comment by njacazio** [comment]
Ciao, voila' https://github.com/ginnocen/MachineLearningHEP/pull/630
