### ISSUE TITLE
Move to new dataset with updated ntracklet subtraction for Lc->pK0s

### ISSUE THREAD

**Issue by ginnocen** [ginnocen/MachineLearningHEP#627]
Hello @DelloStritto. I just opened this issue to make sure we don't forget to update the dataset of the Lc->pK0s. For the moment I added a temporary new database https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_sub.yml.

**Comment by benedikt-voelkel** [comment]
Hej @ginnocen @DelloStritto 

Can we replace 

https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304.yml

with

https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_sub.yml

or do we need both?

**Comment by DelloStritto** [comment]
Hi @benedikt-voelkel . Now that we checked the consistency of the new ntracklets subtraction I think that we can go ahead only with the new databases.

**Comment by benedikt-voelkel** [comment]
Ok, thanks @DelloStritto . Closing...
