### ISSUE TITLE
Remove hardcoded numbers in signal selection

### ISSUE THREAD

**Issue by lvermunt** [ginnocen/MachineLearningHEP#65]
We should get rid of these hardcoded numbers in the signal selection strings in database_ml_parameters.yml
```
  sel_signal: cand_type_ML==10 or cand_type_ML==11 or cand_type_ML==18 or cand_type_ML==19
```
used in 
```
  df_sig = df_sig.query(sel_signal)
```
Especially now we will add the IsSelectedPID and IsSelectedTopo bits in the TreeCreator soon, and probably will start using meson-dependent bits in the same bitmap. 

I did some quick tries with bitwise operations, but these don't seem to work in the query() functions. I found a solution, but it is a bit cumbersome as my Panda Dataframe knowledge is still limited ;-)

```
# For testing
signalmap = 0b0001         #should be stored in database_ml_parameters.yml
df = pd.DataFrame([[2,6,34,0],[1,4,23,1],[2,3,54,2],[4,5,56,3],[3,2,56,4],[6,3,73,5],[9,0,23,6],[7,5,54,7],[8,9,83,8],[3,6,92,9]],columns=['a', 'b', 'c', 'cand_type_ML'])

df_temp = df.query("(cand_type_ML>>signalmap) == 1")                  # Doesn't work
df_temp = df.query("numpy.bitwise_and(cand_type_ML,1) == 1")          # Doesn't work
df_temp = df[df['cand_type_ML'].apply(lambda x: x & signalmap == 1)]  # Works, but cumbersome
```

There should be is a nicer solution. Anyone has a better idea?

**Comment by fcatalan92** [comment]
This point was addressed by #71 and #79. Closing.
