### ISSUE TITLE
Explicit usage of `nsigTOF_Pr_0` breaks efficiency

### ISSUE THREAD

**Issue by benedikt-voelkel** [ginnocen/MachineLearningHEP#688]
The explicit usage of `nsigTOF_Pr_0` in https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/processerdhadrons_mult.py#L409-L410 breaks the code with any database/particle which **does not** extract this field from the produced TTrees (e.g. D0, see https://github.com/ginnocen/MachineLearningHEP/blob/master/machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml)

This was introduced in #673

**Comment by njacazio** [comment]
Yes I will fix it in https://github.com/ginnocen/MachineLearningHEP/pull/687

**Comment by benedikt-voelkel** [comment]
Great, @njacazio Thanks :)

**Comment by njacazio** [comment]
Ok, the PR is ready to be merged

**Comment by njacazio** [comment]
The more general problem that this efficiency w/woTOF is not universal as it depends on the database, one should have several cases depending on what is available e.g. TOF information of any of  Pions/Kaons/Protons

**Comment by benedikt-voelkel** [comment]
That is true. We can discuss this also tomorrow in our meeting, what do you think?

**Comment by njacazio** [comment]
Ok, why not
