### ISSUE TITLE
Include new example of input data with the new dataformat structure

### ISSUE THREAD

**Issue by fcatalan92** [ginnocen/MachineLearningHEP#81]
In the Monte Carlo `SmallSkimmed_*.root` files, downloaded by `ml-get-data`, very few or no signal candidates are present. They are also very small ~100 KB. Probably they could be replaced by bigger files with more data.

At the moment, the code could not work properly using these files.

**Comment by ginnocen** [comment]
@fcatalan92: I changed the issue topic according to the recent changes in the code structure
